name: Deploy to Xenon
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@main

      - name: scp code
        uses: appleboy/scp-action@master
        with:
          host: xenon.stanford.edu
          username: anagao
          password: ${{ secrets.STANFORD_PASSWORD }}
          
          # copy www folder to anagao@xenon.stanford.edu:./
          source: "www"
          target: "."
          overwrite: true
